---
apiVersion: v1
kind: Service
metadata:
  name: person-server-service
spec:
  selector:
#Указываются имена подов, в которые отправляется трафик
    app: person-server
  type: ClusterIp
  ports:
      port: 8081
      targetPort: 8081
      protocol: TCP
...