server:
  port: 8081

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full

service:
#  remote_server_url: localhost:8082
  remote_server_url: ${REMOTE_SERVER_URL:http://remote-node-port:8082}
